# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Download PreliminaryJudge
      run: |
        mkdir -p ${{github.workspace}}/judge-linux
        curl -L https://raw.githubusercontent.com/jankiny/public-bucket/CodeCraft2024/judge-linux/PreliminaryJudge > ${{github.workspace}}/judge-linux/PreliminaryJudge
        chmod +x ${{github.workspace}}/judge-linux/PreliminaryJudge

    - name: Download Map File
      run: |
        mkdir -p ${{github.workspace}}/judge-linux/maps
        curl -L https://raw.githubusercontent.com/jankiny/public-bucket/CodeCraft2024/judge-linux/maps/map1.txt > ${{github.workspace}}/judge-linux/maps/map1.txt
        curl -L https://raw.githubusercontent.com/jankiny/public-bucket/CodeCraft2024/judge-linux/maps/map2.txt > ${{github.workspace}}/judge-linux/maps/map2.txt
        curl -L https://raw.githubusercontent.com/jankiny/public-bucket/CodeCraft2024/judge-linux/maps/map3.txt > ${{github.workspace}}/judge-linux/maps/map3.txt
        curl -L https://raw.githubusercontent.com/jankiny/public-bucket/CodeCraft2024/judge-linux/maps/map4.txt > ${{github.workspace}}/judge-linux/maps/map4.txt
        curl -L https://raw.githubusercontent.com/jankiny/public-bucket/CodeCraft2024/judge-linux/maps/map5.txt > ${{github.workspace}}/judge-linux/maps/map5.txt
        curl -L https://raw.githubusercontent.com/jankiny/public-bucket/CodeCraft2024/judge-linux/maps/map6.txt > ${{github.workspace}}/judge-linux/maps/map6.txt
        curl -L https://raw.githubusercontent.com/jankiny/public-bucket/CodeCraft2024/judge-linux/maps/map7.txt > ${{github.workspace}}/judge-linux/maps/map7.txt
        curl -L https://raw.githubusercontent.com/jankiny/public-bucket/CodeCraft2024/judge-linux/maps/map8.txt > ${{github.workspace}}/judge-linux/maps/map8.txt

    - name: Run Preliminary Judge - map1
      run: |
        ${{github.workspace}}/judge-linux/PreliminaryJudge ${{github.workspace}}/build/CodeCraft2024 -m ${{github.workspace}}/judge-linux/maps/map1.txt
        mv ${{github.workspace}}/log.txt ${{github.workspace}}/log_map1.txt 
        
    - name: Run Preliminary Judge - map2
      run: |
        ${{github.workspace}}/judge-linux/PreliminaryJudge ${{github.workspace}}/build/CodeCraft2024 -m ${{github.workspace}}/judge-linux/maps/map2.txt
        mv ${{github.workspace}}/log.txt ${{github.workspace}}/log_map2.txt 
        
    - name: Run Preliminary Judge - map3
      run: |
        ${{github.workspace}}/judge-linux/PreliminaryJudge ${{github.workspace}}/build/CodeCraft2024 -m ${{github.workspace}}/judge-linux/maps/map3.txt
        mv ${{github.workspace}}/log.txt ${{github.workspace}}/log_map3.txt 
        
    - name: Run Preliminary Judge - map4
      run: |
        ${{github.workspace}}/judge-linux/PreliminaryJudge ${{github.workspace}}/build/CodeCraft2024 -m ${{github.workspace}}/judge-linux/maps/map4.txt
        mv ${{github.workspace}}/log.txt ${{github.workspace}}/log_map4.txt 
        
    - name: Run Preliminary Judge - map5
      run: |
        ${{github.workspace}}/judge-linux/PreliminaryJudge ${{github.workspace}}/build/CodeCraft2024 -m ${{github.workspace}}/judge-linux/maps/map5.txt
        mv ${{github.workspace}}/log.txt ${{github.workspace}}/log_map5.txt 
        
    - name: Run Preliminary Judge - map6
      run: |
        ${{github.workspace}}/judge-linux/PreliminaryJudge ${{github.workspace}}/build/CodeCraft2024 -m ${{github.workspace}}/judge-linux/maps/map6.txt
        mv ${{github.workspace}}/log.txt ${{github.workspace}}/log_map6.txt 
        
    - name: Run Preliminary Judge - map7
      run: |
        ${{github.workspace}}/judge-linux/PreliminaryJudge ${{github.workspace}}/build/CodeCraft2024 -m ${{github.workspace}}/judge-linux/maps/map7.txt
        mv ${{github.workspace}}/log.txt ${{github.workspace}}/log_map7.txt 
        
    - name: Run Preliminary Judge - map8
      run: |
        ${{github.workspace}}/judge-linux/PreliminaryJudge ${{github.workspace}}/build/CodeCraft2024 -m ${{github.workspace}}/judge-linux/maps/map8.txt
        mv ${{github.workspace}}/log.txt ${{github.workspace}}/log_map8.txt 

    - name: Archive Replay and Logs
      run: |
        tar -czvf replay_and_logs.tar.gz -C ${{github.workspace}} replay $(find . -maxdepth 1 -name "*.txt")

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release-${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Replay and Logs Archive
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{github.workspace}}/replay_and_logs.tar.gz
        asset_name: replay_and_logs.tar.gz
        asset_content_type: application/gzip
